# Generated by Django 4.2.6 on 2023-11-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.CharField(max_length=255, unique=True, verbose_name='Location id')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('spot_name', models.CharField(blank=True, max_length=255, verbose_name='Location name')),
                ('spot_address', models.CharField(blank=True, max_length=255, verbose_name='Location address')),
                ('region_id', models.CharField(blank=True, max_length=255, verbose_name='Region id')),
                ('lat', models.CharField(blank=True, max_length=255, verbose_name='Latitude')),
                ('lng', models.CharField(blank=True, max_length=255, verbose_name='longitude')),
                ('image', models.ImageField(blank=True, upload_to='location/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
