# Generated by Django 4.2.6 on 2023-12-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_locationaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='wayforpay_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wayforpay account'),
        ),
        migrations.AddField(
            model_name='location',
            name='wayforpay_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wayforpay key'),
        ),
    ]
