# Generated by Django 4.2.6 on 2024-01-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_wayforpay_account_location_wayforpay_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
    ]
