# Generated by Django 4.2.6 on 2024-01-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_locationimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationimage',
            options={'ordering': ('pk',), 'verbose_name': 'Location mage', 'verbose_name_plural': 'Location images'},
        ),
    ]
