# Generated by Django 4.2.6 on 2024-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_locationimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationaddress',
            options={'verbose_name': 'Shipping address', 'verbose_name_plural': 'Shipping addresses'},
        ),
        migrations.AlterField(
            model_name='locationaddress',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Shipping address'),
        ),
    ]
