# Generated by Django 4.2.6 on 2024-11-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_location_name'),
        ('location', '0007_alter_locationaddress_options_and_more'),
    ]

    operations = [
    ]
