# Generated by Django 4.2.6 on 2023-10-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_signature', models.CharField(max_length=255, verbose_name='SMS_SIGNATURE')),
                ('sms_token', models.CharField(max_length=255, verbose_name='SMS_TOKEN')),
            ],
        ),
    ]
