# Generated by Django 4.2.6 on 2023-10-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_setting_options_setting_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Phone number')),
                ('sms_code', models.CharField(max_length=255, verbose_name='Sms code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
            ],
            options={
                'verbose_name': 'Sms code',
                'verbose_name_plural': 'Sms codes',
            },
        ),
    ]
