# Generated by Django 4.2.6 on 2023-10-26 08:12

from django.db import migrations, models
import sms.models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_smscodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscodes',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[sms.models.validate_phone_is_ukrainian], verbose_name='Phone number'),
        ),
    ]
