# Generated by Django 4.2.6 on 2023-11-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(choices=[('products', 'Products'), ('batchtickets', 'Batch tickets')], unique=True, verbose_name='Title'),
        ),
    ]
