# Generated by Django 4.2.6 on 2023-11-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_type_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product name')),
                ('product_id', models.IntegerField(unique=True, verbose_name='External product id')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.type')),
            ],
            options={
                'verbose_name': 'Product or batch ticket',
                'verbose_name_plural': 'Products or batch tickets',
            },
        ),
    ]
