# Generated by Django 4.2.6 on 2023-11-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtickets',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
