# Generated by Django 4.2.6 on 2023-12-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, unique=True, verbose_name='Location id')),
                ('firstname', models.CharField(max_length=255, verbose_name='First name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last name')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
