# Generated by Django 4.2.6 on 2023-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Client id'),
        ),
    ]
