# Generated by Django 4.2.6 on 2023-12-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Response'),
        ),
    ]
