# Generated by Django 4.2.6 on 2023-12-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_comment_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(verbose_name='Complaints and suggestions')),
            ],
            options={
                'verbose_name': 'Complaints and suggestions',
                'verbose_name_plural': 'Complaints and suggestions',
            },
        ),
    ]
