# Generated by Django 4.2.6 on 2024-01-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_complaints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Feedbacks and complaints', 'verbose_name_plural': 'Feedbacks and complaints'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='Feedbacks and complaints'),
        ),
    ]
