# Generated by Django 4.2.6 on 2024-01-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_wayforpay_account_location_wayforpay_key'),
        ('clients', '0009_proposal_delete_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
