# Generated by Django 4.2.6 on 2024-01-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_wayforpay_account_location_wayforpay_key'),
        ('clients', '0010_comment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
