# Generated by Django 4.2.6 on 2024-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_comment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='registration_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registration token'),
        ),
    ]
