# Generated by Django 4.2.6 on 2024-01-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clients_registration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='registration_token',
            field=models.CharField(blank=True, help_text='Is used by Firebase for sending push notifications', max_length=255, null=True, verbose_name='Registration token'),
        ),
    ]
