# Generated by Django 4.2.6 on 2024-02-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clients_do_not_send_push_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='do_not_send_push_bonus',
            field=models.BooleanField(default=False, verbose_name='Do not send push bonuses'),
        ),
    ]
