# Generated by Django 4.2.6 on 2023-11-18 12:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appsettings',
            managers=[
                ('poster_token', django.db.models.manager.Manager()),
            ],
        ),
    ]
