# Generated by Django 4.2.6 on 2023-11-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_alter_appsettings_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appsettings',
            managers=[
            ],
        ),
    ]
