# Generated by Django 4.2.6 on 2023-12-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_alter_appsettings_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
    ]
