# Generated by Django 4.2.6 on 2024-02-11 11:10

from django.db import migrations
from app_settings.models import AppSettings


def add_time_t1_t2_for_push_migration(apps, schema_editor):
    AppSettings.objects.update_or_create(
        key='t1_service_quality_polling_push',
        defaults={
            'title': 'Время Т1',
            'value': 900,  # 900 s = 15 min
            'description': 'Время T1 в секундах, через которое срабатывает пуш качество услуги. 900 s = 15 min'
        }
    )
    AppSettings.objects.update_or_create(
        key='t2_service_quality_polling_push',
        defaults={
            'title': 'Время Т2',
            'value': 2592000,  # 2592000 s = 30 days
            'description': 'Время T2 в секундах, которое должно пройти после последней отправки пуш качество услуги '
                           'перед тем, как клиент получит следующий пуш качество услуги. 2592000 s = 30 days'
        }
    )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_alter_appsettings_value'),
    ]

    operations = [
        migrations.RunPython(add_time_t1_t2_for_push_migration, reverse_migration)
    ]
