# Generated by Django 4.2.6 on 2024-02-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0006_alter_locationimage_options'),
        ('clients', '0013_alter_clients_registration_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQualityAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clean', models.IntegerField(blank=True, null=True, verbose_name='Cleanliness and sanitation')),
                ('id_products_quality', models.IntegerField(blank=True, null=True, verbose_name='Products quality')),
                ('id_service_quality', models.IntegerField(blank=True, null=True, verbose_name='Service quality')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Service quality answer',
                'verbose_name_plural': 'Service quality answers',
            },
        ),
        migrations.CreateModel(
            name='PushGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('clients', models.ManyToManyField(to='clients.clients')),
            ],
            options={
                'verbose_name': 'Push notifications group',
                'verbose_name_plural': 'Push notifications groups',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('push_notification', 'Push notification'), ('push_notification_service_quality', 'Push notification service quality'), ('push_notification_bonus', 'Push notification service bonus')], default='push_notification', max_length=255, verbose_name='Notification type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('image', models.ImageField(blank=True, null=True, upload_to='push-message/', verbose_name='image')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Client')),
                ('push_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='push.pushgroups', verbose_name='Push notifications group')),
            ],
            options={
                'verbose_name': 'Push message',
                'verbose_name_plural': 'Push messages',
            },
        ),
        migrations.CreateModel(
            name='MessageClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push.message')),
            ],
            options={
                'unique_together': {('message', 'client')},
            },
        ),
    ]
