# Generated by Django 4.2.6 on 2024-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messageclient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('push_notification', 'Push notification'), ('push_notification_service_quality', 'Push notification service quality'), ('push_notification_bonus', 'Push notification bonus')], default='push_notification', max_length=255, verbose_name='Notification type'),
        ),
    ]
