# Generated by Django 4.2.6 on 2024-02-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_clients_registration_token'),
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushgroups',
            name='clients',
            field=models.ManyToManyField(to='clients.clients'),
        ),
    ]
