# Generated by Django 4.2.6 on 2024-02-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_clients_registration_token'),
        ('push', '0002_pushgroups_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushgroups',
            options={'verbose_name': 'Push notifications group', 'verbose_name_plural': 'Push notifications groups'},
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('image', models.ImageField(blank=True, null=True, upload_to='push-message/', verbose_name='Image')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('push_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='push.pushgroups')),
            ],
            options={
                'verbose_name': 'Push message',
                'verbose_name_plural': 'Push messages',
            },
        ),
    ]
