# Generated by Django 4.2.6 on 2024-02-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_alter_messageclient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageclient',
            options={'verbose_name': 'The history of push messages', 'verbose_name_plural': 'The history of push messages'},
        ),
    ]
