# Generated by Django 4.2.6 on 2024-02-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_alter_pushgroups_options_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='push-message/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
