# Generated by Django 4.2.6 on 2024-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_alter_messageclient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageclient',
            name='message',
        ),
        migrations.AddField(
            model_name='messageclient',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='messageclient',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='messageclient',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
