# Generated by Django 4.2.6 on 2024-02-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_clients_registration_token'),
        ('push', '0004_alter_message_body_alter_message_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('push_notification', 'Push notification'), ('push_notification_service_quality', 'Push notification service quality'), ('push_notification_bonus', 'Push notification service bonus')], default='push_notification', max_length=255, verbose_name='Notification type'),
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='push_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='push.pushgroups', verbose_name='Push notifications group'),
        ),
    ]
