# Generated by Django 4.2.6 on 2024-02-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0004_remove_messageclient_message_messageclient_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageclient',
            name='type',
            field=models.CharField(choices=[('push_notification', 'Push notification'), ('push_notification_service_quality', 'Push notification service quality'), ('push_notification_bonus', 'Push notification bonus')], default='push_notification', max_length=255, verbose_name='Notification type'),
        ),
    ]
