# Generated by Django 4.2.6 on 2024-02-18 11:53

from django.db import migrations


def add_message_type_push_notification_bonus(apps, schema_editor):
    Message = apps.get_model('push', 'Message')
    Message.objects.update_or_create(
        type='push_notification_bonus',
        defaults={
            'title': 'Сообщение о бонусах',
            'body': 'Вам начислено %.f грн бонусов. Спасибо за покупку!',
        }
    )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0005_messageclient_type'),
    ]

    operations = [
        migrations.RunPython(add_message_type_push_notification_bonus, reverse_migration)
    ]
