# Generated by Django 4.2.6 on 2024-02-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_clients_registration_token'),
        ('push', '0005_message_type_alter_message_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push.message')),
            ],
        ),
    ]
