# Generated by Django 4.2.6 on 2024-02-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0006_messageclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageclient',
            old_name='created',
            new_name='created_at',
        ),
    ]
