# Generated by Django 4.2.6 on 2024-02-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0006_add_message_type_push_notification_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(help_text='To substitute the bonus amount you should use %.f for integer rounding or %.1f to round to one decimal place', verbose_name='body'),
        ),
    ]
