# Generated by Django 4.2.6 on 2024-02-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_clients_registration_token'),
        ('push', '0007_rename_created_messageclient_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messageclient',
            unique_together={('message', 'client')},
        ),
    ]
