# Generated by Django 4.2.6 on 2024-02-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_clients_registration_token'),
        ('location', '0006_alter_locationimage_options'),
        ('push', '0008_alter_messageclient_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQualityAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clean', models.IntegerField(blank=True, null=True, verbose_name='Cleanliness and sanitation')),
                ('id_products_quality', models.IntegerField(blank=True, null=True, verbose_name='Products quality')),
                ('id_service_quality', models.IntegerField(blank=True, null=True, verbose_name='Service quality')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
