# Generated by Django 4.2.6 on 2024-11-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_transaction_push_quality_service_is_sent'),
        ('push', '0008_message_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.transaction', verbose_name='Client order'),
        ),
    ]
