# Generated by Django 4.2.6 on 2024-12-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0009_alter_message_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageclient',
            name='spot_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='spot_id'),
        ),
    ]
