# Generated by Django 4.2.6 on 2024-02-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0009_servicequalityanswers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicequalityanswers',
            options={'verbose_name': 'Service quality answer', 'verbose_name_plural': 'Service quality answers'},
        ),
        migrations.AddField(
            model_name='servicequalityanswers',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Date created'),
        ),
    ]
