# Generated by Django 4.2.6 on 2024-12-19 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0010_messageclient_spot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageclient',
            name='quality_is_rated',
            field=models.BooleanField(default=False, verbose_name='Quality is rated'),
        ),
        migrations.AddField(
            model_name='servicequalityanswers',
            name='message_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='push.messageclient'),
        ),
    ]
