# Generated by Django 4.2.6 on 2024-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0010_alter_servicequalityanswers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicequalityanswers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created'),
        ),
    ]
