# Generated by Django 4.2.6 on 2024-02-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_clients_registration_token'),
        ('location', '0006_alter_locationimage_options'),
        ('push', '0011_alter_servicequalityanswers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicequalityanswers',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='servicequalityanswers',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Location'),
        ),
    ]
