# Generated by Django 4.2.6 on 2024-02-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='push_is_sent',
            field=models.BooleanField(default=False, verbose_name='Push is sent'),
        ),
    ]
