# Generated by Django 4.2.6 on 2024-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_push_is_sent_transaction_push_quality_service_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='push_quality_service_is_sent',
            field=models.BooleanField(default=False, verbose_name='Push quality service is sent'),
        ),
    ]
